#
# Module manifest for module 'Microsoft365DSC'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2025-11-12

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
  ModuleVersion     = '1.25.1112.1'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '39f599a6-d212-4480-83b3-a8ea2124d8cf'

  # Author of this module
  Author            = 'Microsoft Corporation'

  # Company or vendor of this module
  CompanyName       = 'Microsoft Corporation'

  # Copyright statement for this module
  Copyright         = '(c) 2025 Microsoft Corporation. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  ScriptsToProcess = @(
    'Update-MaximumFunctionCount.ps1'
  )

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules     = @(
    'Modules/M365DSCAgent.psm1',
    'Modules/M365DSCDocGenerator.psm1',
    'Modules/M365DSCErrorHandler.psm1',
    'Modules/M365DSCLogEngine.psm1',
    'Modules/M365DSCPermissions.psm1',
    'Modules/M365DSCReport.psm1',
    'Modules/M365DSCReverse.psm1',
    'Modules/M365DSCStubsUtility.psm1',
    'Modules/M365DSCTelemetryEngine.psm1',
    'Modules/M365DSCUtil.psm1',
    'Modules/M365DSCDRGUtil.psm1',
    'Modules/M365DSCIntuneSettingsCatalogUtil.psm1',
    'Modules/EncodingHelpers/M365DSCEmojis.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureDevOPSHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCDefenderHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCFabricHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCLicensingHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCPowerPlatformRESTHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCServicesHubHelper.psm1',
    'Modules/M365DSCConfigurationHelper.psm1'
  )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  #FunctionsToExport = @()

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @(
    'Assert-M365DSCBlueprint',
    'Compare-M365DSCConfigurations',
    'Confirm-M365DSCDependencies',
    'Export-M365DSCConfiguration',
    'Export-M365DSCDiagnosticData',
    'Get-M365DSCNotificationEndPointRegistration',
    'Get-M365DSCEvaluationRulesForConfiguration',
    'Join-M365DSCConfiguration',
    'New-M365DSCDeltaReport',
    'New-M365DSCNotificationEndPointRegistration',
    'New-M365DSCReportFromConfiguration',
    'New-M365DSCStubFiles',
    'Remove-M365DSCNotificationEndPointRegistration',
    'Set-M365DSCAgentCertificateConfiguration',
    'Split-M365DSCConfiguration',
    'Test-M365DSCAgent',
    'Test-M365DSCDependenciesForNewVersions',
    'Test-M365DSCModuleValidity',
    'Uninstall-M365DSCOutdatedDependencies',
    'Update-M365DSCAllowedGraphScopes',
    'Update-M365DSCAzureAdApplication',
    'Update-M365DSCDependencies',
    'Update-M365DSCModule',
    'Update-M365DSCResourceDocumentationPage',
    'Update-M365DSCResourcesSettingsJSON'
  )

  # Variables to export from this module
  # VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags         = 'DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'Microsoft365'

      # A URL to the license for this module.
      LicenseUri   = 'https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/Microsoft/Microsoft365DSC'

      # A URL to an icon representing this module.
      IconUri      = 'https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true'

      # ReleaseNotes of this module
      ReleaseNotes = '* GCCH/Sovereign Cloud Support
  * Added Environment parameter support to connection infrastructure for GCCH (GCC High) tenants.
  * Updated New-M365DSCConnection to accept and pass Environment parameter to MSCloudLoginAssistant.
  * Fixed hardcoded login endpoints to dynamically detect government cloud tenants (.us domains).
  * Added Environment parameter to AADApplication resource as proof-of-concept implementation.
  * Note: USGov environment covers both GCC and GCC High (GCCH) tenants.
  * Environment values: Global (commercial), USGov (GCC/GCCH), USGovDoD (DoD), China, Germany.
  * Resources must be updated individually to expose Environment parameter (see GCCH_IMPLEMENTATION_GUIDE.md).
* AADApplication
  * Added support for `TokenLifetimePolicies`.
  * Fixing issue where Set-TargetResource threw an error trying to recreate
    an existing permissions scope when id was not provided.
* AADFeatureRolloutPolicy
  * Added support for `AppliesTo`.
* AADFilteringPolicyRule
  * Fixed issue retrieving existing rule where the Id parameter was incorrectly provided.
* AADGroup
  * Fixed an issue where using advanced filtering during export failed.
  * Updated the required permissions to match the used cmdlets.
* AADUser
  * Added new permission requirement `User.EnableDisableAccount.All` for enabling / disabling accounts.
* EXOIRMConfiguration
  * Fixed an issue where the `LicensingLocation` property was not exported correctly.
    FIXES [#6644](https://github.com/microsoft/Microsoft365DSC/issues/6644)
* IntuneAlertRuleWindows365
  * Initial release.
* IntuneAppProtectionPolicyAndroid
  * Fixes an issue where Set-TargetResource attempted to create an additional policy
    when two instances with the same name already existed.
* IntuneAppProtectionPolicyiOS
  * Fixes an issue where Set-TargetResource attempted to create an additional policy
    when two instances with the same name already existed.
* IntuneDeviceConfigurationHealthMonitoringConfigurationPolicyWindows10
  * Fixed an issue where the resource failed with `ModelValidationFailure` due to property casing mismatch.
* IntuneDeviceControlPolicySetting
  * Initial release.
* IntuneEpmCertificatePolicySetting
  * Initial release.
* IntuneFirewallPolicySetting
  * Initial release.
* IntuneManagedInstallerPolicyWindows10
  * Initial release.
* IntuneSettingCatalogCustomPolicyWindows10
  * Fixed issue where roleScopeTagIds was sent as null instead of array, causing BadRequest (400) during policy update.
* ODSettings
  * Fixed an issue where exporting `DomainGuids` would throw because it is a GUID type.
    FIXES [#6615](https://github.com/microsoft/Microsoft365DSC/issues/6615)
* SPOSharingSettings
  * Changed from server-side filtering to local because of backend limitations.
    FIXES [#6631](https://github.com/microsoft/Microsoft365DSC/issues/6631)
* SCDLPSensitiveInformationType
  * Initial release.
* TeamsAIPolicy
  * Initial release.
* TeamsFederationConfiguration
  * Fixed an issue where `AllowedDomains` could not be set.
    FIXES [#6654](https://github.com/microsoft/Microsoft365DSC/issues/6654)
* TeamsMeetingPolicy
  * Added support for new properties.
    FIXES [#6606](https://github.com/microsoft/Microsoft365DSC/issues/6606)
* TeamsMessagingPolicy
  * Fixed an issue where `UseB2BInvitesToAddExternalUsers` was exported with the wrong value.
    FIXES [#6632](https://github.com/microsoft/Microsoft365DSC/issues/6632)
* TeamsUpdateManagementPolicy
  * Fixed an issue where the type for `DisabledInProductMessages` was String instead of a String array.
    FIXES [#6635](https://github.com/microsoft/Microsoft365DSC/issues/6635)
* TeamsVoiceRoutingPolicy
  * Fixed an issue where removing a policy required PSTN usages to exist.
    FIXES [#6449](https://github.com/microsoft/Microsoft365DSC/issues/6649)
* VivaEngagementRoleMember
  * Fixed issue loading the required modules to export this resource.
* M365DSCDRGUtil
  * Added drift event message to Verbose output.
    FIXES [#6666](https://github.com/microsoft/Microsoft365DSC/issues/6666).
  * Fixed issue loading the required modules to export this resource
* M365DSCReverse
  * Fixed an issue where having resources specified in both include and exclude
    during export would result in an exception.
    FIXES [#6630](https://github.com/microsoft/Microsoft365DSC/issues/6630)
* M365DSCUtil
  * Added custom post processing to `Test-M365DSCTargetResource`.
  * Improved logging output of `Test-M365DSCTargetResource`.
  * Added new function `Split-M365DSCConfiguration`.
  * Moved resource initialization into dedicated function.
  * Removed groupId requirement in `ConvertTo-IntuneMobileAppAssignment`.
* MISC
  * Centralized more resource testing to the testing function.
  * Updated single instance information retrieval in EXO resources.
    FIXES [#6643](https://github.com/microsoft/Microsoft365DSC/issues/6643)
  * Improved support for `ErrorAction` during export.
    FIXES [#6610](https://github.com/microsoft/Microsoft365DSC/issues/6610)
* DEPENDENCIES
  * Updated MSCloudLoginAssistant to version 1.1.54'

      # Flag to indicate whether the module requires explicit user acceptance for install/update
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}
